CREATE SEQUENCE IF NOT EXISTS accommodation_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS countries_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS host_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE accommodation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    category   VARCHAR(255)                            NOT NULL,
    condition  VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    num_rooms  INTEGER                                 NOT NULL,
    rented     BOOLEAN                                 NOT NULL,
    host_id    BIGINT,
    CONSTRAINT accommodation_pkey PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    continent VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE host
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,
    country_id BIGINT,
    CONSTRAINT host_pkey PRIMARY KEY (id)
);

CREATE TABLE hosts
(
    country_id INTEGER,
    id         INTEGER,
    name       INTEGER,
    created_at INTEGER,
    surname    INTEGER,
    updated_at INTEGER
);

ALTER TABLE host
    ADD CONSTRAINT fktli34xykkoqlgdbbegov5r43r FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE NO ACTION;

ALTER TABLE accommodation
    ADD CONSTRAINT fkxlitwn68lomveiyomtuuys4a FOREIGN KEY (host_id) REFERENCES host (id) ON DELETE NO ACTION;