services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql   # <--- mount at /var/lib/postgresql

volumes:
  pgdata: